### ISSUE TITLE
Last.fm "Remove Featured Artists" and "Remove Album Extensions" also affects Discord RPC

### ISSUE THREAD

**Issue by n-1-c-k-y** [ciderapp/Cider-2#660]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store / Discord

### Operating System

Windows, Tested it on Linux too

### Describe the Bug

When your LFM account is connected and the track adjustments 'Remove Featured Artists' and 'Remove Album Extensions' are enabled, it will also affect the Discord RPC, removing the featured artists and the album extensions in the RPC too.

### Steps to Reproduce

1. Connect LFM account
2. Enable 'Removed Feature Artists' or 'Remove Album Extensions' in Track Adjustments
3. Check the Discord RPC

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/55335959/b8fb5d46-cc74-48ac-b79c-492eefaeaf39) (Disabled)
![image](https://github.com/ciderapp/Cider-2/assets/55335959/51a73942-6a38-4322-a6bb-1bd8558af54d) (Enabled)

**Comment by coredev-uk** [comment]
Should be fixed in 2.4.2

**Comment by n-1-c-k-y** [comment]
> Should be fixed in 2.4.2

I just tested the new .NET version, and this still happens. Was it fixed only for Sabiiro/Electron?

**Comment by n-1-c-k-y** [comment]
bump

**Comment by coredev-uk** [comment]
@n-1-c-k-y can you test on the latest experimental Linux build please

**Comment by n-1-c-k-y** [comment]
I just tested it and it's still doing the same thing.

{"version":"2.5.4","commit":"5619924b8d8c8cede3fb3696210c8b5b99bb81b1","buildDate":"1732130632027","framework":"genten","isDev":"production","platform":"linux","platformFriendly":"Linux","platformVersion":"6.6.59-1-lts","arch":"x64","port":"10767","steamdeck":false,"clientVersion":"2.0.0","protocolVersion":"4","capi":"csevd680hwh903mtglciytiw"}

**Comment by coredev-uk** [comment]
@n-1-c-k-y I have just pushed another build to Taproom. Give that a try, but be aware that Taproom has been caching builds, so make sure you clear your cache and make sure the checksum or file creation date does not match your current build.

**Comment by n-1-c-k-y** [comment]
I think it is now completely broken

**Comment by coredev-uk** [comment]
Yeah I did break lastfm, a build was just pushed that should fix it. In my testing this issue is no longer present

**Comment by n-1-c-k-y** [comment]
My bad, I thought it didn't happen anymore in your tests; I just tested it and it's still doing the same thing.

**Comment by coredev-uk** [comment]
What build did you use, because it is physically impossible for it to happen in the latest. Please remove the spa.zip in your appdata and use the latest experimental genten build

**Comment by n-1-c-k-y** [comment]
> What build did you use, because it is physically impossible for it to happen in the latest. Please remove the update.zip in your appdata and use the latest experimental genten build

I'm using the latest experimental appimage.

![image](https://github.com/user-attachments/assets/94bacc68-6f42-4fae-a9ee-eeb30053e0e3)
![image](https://github.com/user-attachments/assets/3cff0b35-9551-4dd3-83bc-f4254344acb5)
![image](https://github.com/user-attachments/assets/f5c5bd0a-7975-4bb0-aa6d-2dfa9e046ca1)

With remove featured artists disabled:
![image](https://github.com/user-attachments/assets/04f0adc5-4b4a-4fc5-bc7a-f7ae02790083)

 I already tried deleting the sh.cider.genten folder entirely, and it didn't work.


{"buildInfo":{"version":"2.5.4.0","commit":"1222aefb3170dac55de90fb4b08a5bf95632152b","buildDate":"1732280265092","changelogUrl":"2.5.0-release"},"clientInfo":{"client":"genten","env":"production","arch":"x64","platform":"linux","platformFriendly":"Linux","build":"desktop","clientVersion":"2.0.0","capi":"j1i9i4gguakzsrk1mmyuuj4k"}}

**Comment by n-1-c-k-y** [comment]
I was getting an older build; I downloaded and extracted the rpm, and I got a more recent build, yet the issue persists.

{"buildInfo":{"version":"2.5.4.0","commit":"38f06753747557498950f0d3fd765ba33580bab9","buildDate":"1732335990530","changelogUrl":"2.5.0-release"},"clientInfo":{"client":"genten","env":"production","arch":"x64","platform":"linux","platformFriendly":"Linux","build":"desktop","clientVersion":"2.0.0","capi":"q2ccb55h2m2xkgte1wi4tsiy"}}

**Comment by coredev-uk** [comment]
Okay, I finally see what you mean. It seems the mutations we were making to the event object were being carried to the main musickit nowplayingitem, which is incredibly stupid. I have made a fix that clones it. Sorry about the confusion

**Comment by n-1-c-k-y** [comment]
It looks like it's broken again and not removing the featured artists in the scrobbles now.
![image](https://b.catgirlsare.sexy/2icwIq72bS37.png)
![image](https://b.catgirlsare.sexy/ZyGqma-PVbPn.png)
![image](https://b.catgirlsare.sexy/M4R5O8Mj7vLI.png)

**Comment by coredev-uk** [comment]
Ill add the check in, didnt think isCloudItem would not be present

**Comment by coredev-uk** [comment]
The build is currently uploading to Taproom, should fix this @n-1-c-k-y

**Comment by n-1-c-k-y** [comment]
{"version":"2.5.4.0-ptb75","commit":"92ad8bb117781fdb0dd4fb9fd69f2489c3b95ad9","buildDate":"1730849075986","framework":"electron","isDev":"production","platform":"linux","platformFriendly":"Linux","platformVersion":"6.6.59-1-lts","arch":"x64","port":"10767","steamdeck":false,"clientVersion":"3","capi":"htvudy124oy7w92v446vuagv"}

This?

**Comment by coredev-uk** [comment]
Yeah, thanks. It seems the object cloning didnt do anything, Im working on restructuring the function so it should work, i'll let you know when the builds are up.

**Comment by n-1-c-k-y** [comment]
No problem, happy to help.

**Comment by coredev-uk** [comment]
Ok, I've just committed it, give it about 5-10 minutes to build, check the build time on taproom.

**Comment by n-1-c-k-y** [comment]
Yeah, it's fixed now, thanks!
