### ISSUE TITLE
White borders around the app when fullscreen

### ISSUE THREAD

**Issue by amidstacy** [ciderapp/Cider-2#720]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

3baa7bbffd664e9dfcd1847204c49a8b2eee5962

### Connect Instance ID

not-logged-in

### Build Timestamp

8/17/2024, 5:00:06 AM

### Describe the Bug

White borders around the app, could this be a Cider problem or a scaling problem on my side? (please be the former) It only happens on Cider + the white borders disappear when it's minimized.

### Steps to Reproduce

I don't know

### Anything else?

fullscreen:

![image_2024-08-17_214910063](https://github.com/user-attachments/assets/c73bdfc6-e0dc-4515-91c4-2b2f7b1e54b5)

minimized:
![image_2024-08-17_214947843](https://github.com/user-attachments/assets/ab82964e-fe35-4489-9bab-f2722509c16e)

here's a video if needed, it also shows on album covers when it's animated (apologies for the bitrate starved video, it shows the problem anyway): https://streamable.com/lw6ctd

**Comment by coredev-uk** [comment]
Resolved in next release.

**Comment by amidstacy** [comment]
Hello, I'm on 2.5.2 Patch 3 and I still see the borders 
![image](https://github.com/user-attachments/assets/03bb3bdb-a2ad-4788-bd07-e3472bcfd939)
