### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by JustSxm** [ciderapp/Cider-2#780]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

57a19b9cfd45f52a28be6b1e8d456f73d151aa2d

### Build Timestamp

2024-09-13, 10:43:51 p.m.

### Describe the Bug

When searching for a query with no results, instead of showing something as "No results." we get an infinite loading spinner.

This happens as well when searching for an existing result and scrolling at the bottom

(There also seems to be 2 spinners, one quickly dissapear)

Here is a demo:
https://streamable.com/k0xkm2

### Steps to Reproduce

Here is a demo:
https://streamable.com/k0xkm2

**Comment by JustSxm** [comment]
bump

**Comment by coredev-uk** [comment]
Please ensure your application is up-to-date. There was an outage with the Apple Music API earlier on, but we believe this is resolved.

**Comment by JustSxm** [comment]
Still happening. It is up to date. I believe if there is no result the application just not remove the loading

**Comment by coredev-uk** [comment]
Have you tried resetting your settings and/or checked your storefront settings found in Settings > General > Apple Music > storefront, please ensure this value is either set to 'auto' if available or your primary account region.

If the above did not work, please could you provide the following:
1. The outcome of what happened when you completed the same action on the Apple Music website
2. What is outputted in your console (Ctrl+Shift+I -> console) when you attempted this actions 
3. What type of Apple Music subscription you have
