### ISSUE TITLE
Lyrics Translation Language is missing.

### ISSUE THREAD

**Issue by MrDirectory** [ciderapp/Cider-2#825]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

macOS 15.1

### Commit Hash

7b04e2c902aa2dab4065c276beb3302b22385240

### Build Timestamp

10/29/2024, 2:16:42 PM

### Describe the Bug

When Lyrics Translation is enabled, the translation language is missing.
It showed up in 2.5.0, but not currently in 2.5.4 Patch 3.
<img width="1772" alt="Screenshot 2024-11-05 at 6 05 39 PM" src="https://github.com/user-attachments/assets/ece71712-7195-4fc7-aba1-32a2e42c6b4a">

### Steps to Reproduce

1. Go to Settings.
2. Select Visual.
3. Click on Lyrics.
4. Enable Lyrics Translation.
5. Lyrics Translation Language should appear, but currently it doesn't.

### Anything else?

Here's 2.5.0 for comparison.
<img width="1772" alt="Screenshot 2024-11-05 at 6 09 47 PM" src="https://github.com/user-attachments/assets/d4e951eb-fbaf-47ec-9de0-d8805e55074c">

**Comment by coredev-uk** [comment]
A result of the rewrite afaik. @Monochromish if you can take a look ty

**Comment by coredev-uk** [comment]
Fixed in https://github.com/ciderapp/citadel/commit/4c6d9a9d5b5156cfe30f1d2792f11ab84ee87615

**Comment by MrDirectory** [comment]
New build on Taproom still doesn't fix the issue.
<img width="1670" alt="Screenshot 2024-12-02 at 1 29 50 AM" src="https://github.com/user-attachments/assets/6f66baa5-4660-4783-a3e2-ced8da988540">

**Comment by coredev-uk** [comment]
The new build is yet to be released, as you can see by the timestamp on Taproom.

**Comment by MrDirectory** [comment]
Has the build with the fix been uploaded to Taproom yet?

**Comment by coredev-uk** [comment]
It was about 10 hours ago

**Comment by MrDirectory** [comment]
Unfortunately, the build didn't fix the issue.
<img width="1670" alt="Screenshot 2024-12-07 at 12 39 51 PM" src="https://github.com/user-attachments/assets/9c771431-c48a-4aeb-9d68-417decf781f7">

**Comment by MrDirectory** [comment]
Fixed in Windows.
![Screenshot 2024-12-09 084103](https://github.com/user-attachments/assets/d85d34ca-d0ce-4b24-878a-7b035282225d)

**Comment by MrDirectory** [comment]
Fixed in Windows.
![Screenshot 2024-12-09 084207](https://github.com/user-attachments/assets/0c83cca9-159a-4227-9eb7-73e1545ea415)
