### ISSUE TITLE
"Close to tray" didn't work on 2.6.0

### ISSUE THREAD

**Issue by MareDevi** [ciderapp/Cider-2#889]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

itch.io

### Operating System

Arch linux hyprland

### Describe the Bug

"Close to tray" didn't work on 2.6.0

### Steps to Reproduce

open app
the try to close the app window
It will kill the app instead of stay in tray

**Comment by kmf** [comment]
Same issue, NixOS 24.11, GNOME

**Comment by coredev-uk** [comment]
I am going to assume this is using system shortcuts, such as the quit one in Hyprland. In this case, I can say this is resolved and the fix will be available in the next release. 

Resolved with: https://github.com/ciderapp/citadel/commit/90948d73cf34bd2202fd6c9ba5cb7e89214d8976

**Comment by coredev-uk** [comment]
Please retry on the latest experimental release on taproom.

**Comment by MareDevi** [comment]
> Please retry on the latest experimental release on taproom.

I tried the experimental release but it still didn't work🥲

**Comment by komorobi** [comment]
> Please retry on the latest experimental release on taproom.

I have tryed in version 2.6.1, but "Close to tray" still didn't work.
My operating system is ArchLinux KDE wayland. The pacage is deb.

**Comment by kmf** [comment]
Still broken.

**Comment by coredev-uk** [comment]
Resolved in the latest experimental release on taproom.

**Comment by kmf** [comment]
Tested, AppImage it's working for me.

**Comment by samic05** [comment]
Still broken to me, just used the release on the taproom, should I execute it using any flag ??
