### ISSUE TITLE
Animate Artwork broken on Discord RPC

### ISSUE THREAD

**Issue by wisegalang** [ciderapp/Cider-2#958]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [x] I have confirmed that no [support FAQ](https://cider.sh/docs/client/faqs) resolves my issue.
- [x] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [x] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

Taproom

### App Information

{"clientInfo":{"client":"dotnet","env":"production","arch":"AMD64","platform":"win32","platformFriendly":"Windows","build":"desktop","clientVersion":"1.0.0","capi":"5f5c7347-2357-4fcc-bc5e-7c072eb576bd"},"buildInfo":{"version":"2.6.1.0-ptb158","commit":"d5cbb8ca86fca0bcb4fd064ab6456a80dc121a82","buildDate":"1739747993403","changelogUrl":"2.6.0-release"}}

### Operating System

Windows

### OS Version

Windows 11 24H2

### How would you describe your issue?

Integration: DiscordRPC

### Commit Hash

d5cbb8ca86fca0bcb4fd064ab6456a80dc121a82

### Describe the Bug

The animate artwork from this album https://music.apple.com/id/album/ive-mine-ep/1709569466 works fine on cider app itself, either in album page, immersive mode, or mini player. But it broke in discord rpc, honestly i don't know if this bug from cider or just an issue by apple but i'll just report this issue.

another info: i don't remember exactly in what version. But the animate artwork from this album https://music.apple.com/id/album/supernatural-single/1750576829 also broken, but it doesn't show the question mark icon like in the picture I sent, it shows the cider app logo but unfortunately I didn't get a screenshot and now the animate album is working fine like before on discord rpc.

![Image](https://github.com/user-attachments/assets/d2afceed-d51a-455a-8212-41f99cc0c535)

### Steps to Reproduce

Just play any songs from the album.

**Comment by cryptofyre** [comment]
Update Cider, older versions no longer support this feature due to API changes.

**Comment by wisegalang** [comment]
i already on newest version of cider 2.1.6.4 and tried 2.6.1 PTB 158, it's the only album that broken on discord rpc i've found.

**Comment by cryptofyre** [comment]
Could you provide the album link?

**Comment by wisegalang** [comment]
here you go https://music.apple.com/id/album/ive-mine-ep/1709569466

**Comment by wisegalang** [comment]
i saw someone in discord do this related artwork problem, i hope this one can help something

<img width="888" alt="Image" src="https://github.com/user-attachments/assets/2d5e0933-6375-494b-b7b8-531c7c1a06f4" />

**Comment by cryptofyre** [comment]
This has been fixed.

**Comment by wisegalang** [comment]
Hi, the bug still present at me. I've been trying update Cider to the latest 2.6.1.9 and PTB 156 and reinstall some version of Discord, but still the same.

![Image](https://github.com/user-attachments/assets/1bb19363-a4b5-409f-8f37-51e854a75a1a)

**Comment by cryptofyre** [comment]
This is an error on Discord's end, I can't fix this.

**Comment by wisegalang** [comment]
Alright, thank you for the confirmation and the hard work for this issue. Appriciated it so much!
